var obj = [
    ["navigator.mediaDevices.getUserMedia",
        null,
        {
            "audio": false,
            "video": {
                "mandatory": {
                    "minWidth": 640,
                    "minHeight": 360,
                    "maxWidth": 1280,
                    "maxHeight": 720
                }
            }
        },
        1545894234807],
    [
        "navigator.mediaDevices.getUserMediaOnSuccess",
        null,
        {
            "id": "{744b1f0c-5980-493f-b96d-741dd145027e}",
            "tracks": [
                {
                    "id": "{5ab82c1a-b739-4e45-9ed8-a8a1962e0db7}",
                    "kind": "video",
                    "label": "Aoni HD Camera",
                    "enabled": true,
                    "muted": false,
                    "readyState": "live"
                }
            ]
        },
        1545894236657
    ],
    [
        "create",
        "PC_0",
        {
            "nullConfig": true,
            "browserType": "moz/webkit"
        },
        1545894395130
    ],
    [
        "addStream",
        "PC_0",
        "{0c826850-cb69-4a7f-81a2-67e706bf9088} video:{bdeaac3a-2cb9-4f6a-a43c-9895a42a6e99}",
        1545894395130
    ],
    [
        "createOffer",
        "PC_0",
        null,
        1545894395133
    ],
    [
        "onnegotiationneeded",
        "PC_0",
        1545894395135
    ],
    [
        "createOfferOnSuccess",
        "PC_0",
        {
            "type": "offer",
            "sdp": ""
        },
        1545894395135
    ],
    [
        "setLocalDescription",
        "PC_0",
        {
            "type": "offer",
            "sdp": ""
        },
        1545894395136
    ],
    [
        "onsignalingstatechange",
        "PC_0",
        "have-local-offer",
        1545894395138
    ],
    [
        "setLocalDescriptionOnSuccess",
        "PC_0",
        1545894395138
    ],
    [
        "onicegatheringstatechange",
        "PC_0",
        "gathering",
        1545894395138
    ],
    [
        "onicecandidate",
        "PC_0",
        {
            "candidate": "candidate:0 1 UDP 2122187007 192.168.131.174 59562 typ host",
            "sdpMid": "0",
            "sdpMLineIndex": 0,
            "usernameFragment":"7Yy7"   // chrome有
        },
        1545894395141
    ],
    [
        "onicegatheringstatechange",
        "PC_0",
        "complete",
        1545894395150
    ],
    [
        "onicecandidate",
        "PC_0",
        null,
        1545894395240
    ],
    [
        "setRemoteDescription",
        "PC_0",
        {
            "type": "offer",
            "sdp": ""
        },
        1545894395185
    ],
    [
        "onsignalingstatechange",
        "PC_0",
        "have-remote-offer",
        1545894395206
    ],
    [
        "ontrack",
        "PC_0",
        "video:{0ad5d54a-a726-48d1-abc4-9c34cb810094} stream:{0c826850-cb69-4a7f-81a2-67e706bf9088}",
        1545894395208
    ],
    [
        "onaddstream",
        "PC_0",
        "{0c826850-cb69-4a7f-81a2-67e706bf9088} video:{0ad5d54a-a726-48d1-abc4-9c34cb810094}",
        1545894395208
    ],
    [
        "setRemoteDescriptionOnSuccess",
        "PC_0",
        1545894395210
    ],
    [
        "createAnswer",
        "PC_0",
        null,
        1545894395210
    ],
    [
        "createAnswerOnSuccess",
        "PC_0",
        {
            "type": "answer",
            "sdp": ""
        },
        1545894395212
    ],
    [
        "addIceCandidate",
        "PC_0",
        {
            "candidate": "candidate:0 1 UDP 2122252543 192.168.131.174 59570 typ host",
            "sdpMid": "0",
            "sdpMLineIndex": 0
        },
        1545894395243
    ],
    [
        "addIceCandidateOnSuccess",
        "PC_0",
        1545894395243
    ],
    [
        "oniceconnectionstatechange",
        "PC_0",
        "checking/connected",
        1545894395248
    ]
];

var obj_stats=[
    [
        "getstats",
        "PC_0",
        {
            "3829": {
                "id": "3829",
                "timestamp": 1545894397140,
                "type": "remote-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "portNumber": 9,
                "transport": "tcp"
            },
            "outbound_rtcp_video_0": {
                "id": "outbound_rtcp_video_0",
                "timestamp": 583884252,
                "type": "inbound-rtp",
                "isRemote": true,
                "kind": "video",
                "mediaType": "video",
                "remoteId": "outbound_rtp_video_0",
                "ssrc": 3478749281,
                "bytesReceived": 0,
                "jitter": 0,
                "packetsLost": 0,
                "packetsReceived": 0,
                "_isRemote": true
            },
            "outbound_rtp_video_0": {
                "id": "outbound_rtp_video_0",
                "timestamp": 1545894397140,
                "type": "outbound-rtp",
                "bitrateMean": 4160000,
                "bitrateStdDev": 0,
                "firCount": 0,
                "framerateMean": 1,
                "framerateStdDev": 0,
                "isRemote": false,
                "kind": "video",
                "mediaType": "video",
                "nackCount": 0,
                "pliCount": 0,
                "remoteId": "outbound_rtcp_video_0",
                "ssrc": 3478749281,
                "bytesSent": 14085,
                "droppedFrames": 3857049062,
                "framesEncoded": 1,
                "packetsSent": 45,
                "_isRemote": false
            },
            "pPIg": {
                "id": "pPIg",
                "timestamp": 1545894397140,
                "type": "candidate-pair",
                "bytesReceived": 0,
                "bytesSent": 0,
                "componentId": 1,
                "lastPacketReceivedTimestamp": 0,
                "lastPacketSentTimestamp": 0,
                "localCandidateId": "xz2d",
                "nominated": false,
                "priority": 9115005270282338000,
                "readable": true,
                "remoteCandidateId": "vDnu",
                "selected": false,
                "state": "inprogress",
                "transportId": "transport_0",
                "writable": true
            },
            "oHhD": {
                "id": "oHhD",
                "timestamp": 1545894397140,
                "type": "candidate-pair",
                "bytesReceived": 886,
                "bytesSent": 15699,
                "componentId": 1,
                "lastPacketReceivedTimestamp": 305494909028,
                "lastPacketSentTimestamp": 305494909129,
                "localCandidateId": "rqGx",
                "nominated": true,
                "priority": 9114723795305628000,
                "readable": true,
                "remoteCandidateId": "vDnu",
                "selected": true,
                "state": "succeeded",
                "transportId": "transport_0",
                "writable": true
            },
            "h+KW": {
                "id": "h+KW",
                "timestamp": 1545894397140,
                "type": "candidate-pair",
                "bytesReceived": 0,
                "bytesSent": 0,
                "componentId": 1,
                "lastPacketReceivedTimestamp": 0,
                "lastPacketSentTimestamp": 0,
                "localCandidateId": "DQgW",
                "nominated": false,
                "priority": 9114442320328917000,
                "readable": true,
                "remoteCandidateId": "vDnu",
                "selected": false,
                "state": "inprogress",
                "transportId": "transport_0",
                "writable": true
            },
            "rqGx": {
                "id": "rqGx",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "mozLocalTransport": "udp",
                "portNumber": 59562,
                "transport": "udp"
            },
            "xz2d": {
                "id": "xz2d",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.28.1",
                "mozLocalTransport": "udp",
                "portNumber": 59563,
                "transport": "udp"
            },
            "DQgW": {
                "id": "DQgW",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.42.1",
                "mozLocalTransport": "udp",
                "portNumber": 59564,
                "transport": "udp"
            },
            "sJz8": {
                "id": "sJz8",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "mozLocalTransport": "tcp",
                "portNumber": 55749,
                "transport": "tcp"
            },
            "uCfx": {
                "id": "uCfx",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.28.1",
                "mozLocalTransport": "tcp",
                "portNumber": 59364,
                "transport": "tcp"
            },
            "Vbgp": {
                "id": "Vbgp",
                "timestamp": 1545894397140,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.42.1",
                "mozLocalTransport": "tcp",
                "portNumber": 60386,
                "transport": "tcp"
            },
            "vDnu": {
                "id": "vDnu",
                "timestamp": 1545894397140,
                "type": "remote-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "portNumber": 59570,
                "transport": "udp"
            },
            "timestamp": "2018-12-27T07:06:37.159Z"
        },
        1545894397159
    ],
    [
        "getstats",
        "PC_0",
        {
            "inbound_rtp_video_0": {
                "id": "inbound_rtp_video_0",
                "timestamp": 1545894397188,
                "type": "inbound-rtp",
                "bitrateMean": 6.529903391507e-312,
                "bitrateStdDev": 0,
                "firCount": 0,
                "framerateMean": 1e-323,
                "framerateStdDev": 6.95294459629007e-310,
                "isRemote": false,
                "kind": "video",
                "mediaType": "video",
                "nackCount": 0,
                "pliCount": 0,
                "ssrc": 0,
                "bytesReceived": 14535,
                "discardedPackets": 0,
                "framesDecoded": 0,
                "jitter": 0,
                "packetsLost": 0,
                "packetsReceived": 46,
                "_isRemote": false
            },
            "ZJ6E": {
                "id": "ZJ6E",
                "timestamp": 1545894397188,
                "type": "candidate-pair",
                "bytesReceived": 0,
                "bytesSent": 0,
                "componentId": 1,
                "lastPacketReceivedTimestamp": 0,
                "lastPacketSentTimestamp": 0,
                "localCandidateId": "f0mV",
                "nominated": false,
                "priority": 9115005270282338000,
                "readable": true,
                "remoteCandidateId": "Iftg",
                "selected": false,
                "state": "cancelled",
                "transportId": "transport_0",
                "writable": true
            },
            "NmY0": {
                "id": "NmY0",
                "timestamp": 1545894397188,
                "type": "candidate-pair",
                "bytesReceived": 16165,
                "bytesSent": 886,
                "componentId": 1,
                "lastPacketReceivedTimestamp": 305494909188,
                "lastPacketSentTimestamp": 305494909024,
                "localCandidateId": "f0mV",
                "nominated": true,
                "priority": 9114723795305628000,
                "readable": true,
                "remoteCandidateId": "sVG/",
                "selected": true,
                "state": "succeeded",
                "transportId": "transport_0",
                "writable": true
            },
            "f0mV": {
                "id": "f0mV",
                "timestamp": 1545894397188,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "mozLocalTransport": "udp",
                "portNumber": 59570,
                "transport": "udp"
            },
            "RwhD": {
                "id": "RwhD",
                "timestamp": 1545894397188,
                "type": "local-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "mozLocalTransport": "tcp",
                "portNumber": 63628,
                "transport": "tcp"
            },
            "sVG/": {
                "id": "sVG/",
                "timestamp": 1545894397188,
                "type": "remote-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.131.174",
                "portNumber": 59562,
                "transport": "udp"
            },
            "Iftg": {
                "id": "Iftg",
                "timestamp": 1545894397188,
                "type": "remote-candidate",
                "candidateType": "host",
                "componentId": "transport_0",
                "ipAddress": "192.168.28.1",
                "portNumber": 59563,
                "transport": "udp"
            },
            "timestamp": "2018-12-27T07:06:37.199Z"
        },
        1545894397199
    ],
    [
        "getstats",
        "PC_0",
        {
            "outbound_rtcp_video_0": {
                "bytesReceived": 19530,
                "jitter": 0.002,
                "packetsReceived": 66,
                "roundTripTime": 3
            },
            "outbound_rtp_video_0": {
                "bitrateMean": 1422941.3333333335,
                "bitrateStdDev": 2370362.3369816975,
                "framerateMean": 13.666666666666666,
                "framerateStdDev": 10.96965511460289,
                "bytesSent": 64795,
                "framesEncoded": 40,
                "packetsSent": 106
            },
            "oHhD": {
                "bytesReceived": 1166,
                "bytesSent": 67585,
                "lastPacketReceivedTimestamp": 305494910944,
                "lastPacketSentTimestamp": 305494911126
            },
            "timestamp": "2018-12-27T07:06:39.148Z"
        },
        1545894399148
    ],
    [
        "getstats",
        "PC_0",
        {
            "inbound_rtp_video_0": {
                "bitrateMean": 29755,
                "bitrateStdDev": 42079.92454841144,
                "framerateMean": 21,
                "framerateStdDev": 0,
                "remoteId": "inbound_rtcp_video_0",
                "ssrc": 3478749281,
                "bytesReceived": 66751,
                "framesDecoded": 40,
                "jitter": 0.002,
                "packetsReceived": 108
            },
            "inbound_rtcp_video_0": {
                "id": "inbound_rtcp_video_0",
                "timestamp": 583886296,
                "type": "outbound-rtp",
                "isRemote": true,
                "kind": "video",
                "mediaType": "video",
                "remoteId": "inbound_rtp_video_0",
                "ssrc": 3478749281,
                "bytesSent": 17640,
                "packetsSent": 63,
                "_isRemote": true
            },
            "NmY0": {
                "bytesReceived": 69573,
                "bytesSent": 1242,
                "lastPacketReceivedTimestamp": 305494911181,
                "lastPacketSentTimestamp": 305494911182
            },
            "timestamp": "2018-12-27T07:06:39.190Z"
        },
        1545894399190
    ],

];

var obj_stats_chrome=[
    [
        "getstats",
        "PC_0",
        {
            "googLibjingleSession_3269048889845270929": {
                "id": "googLibjingleSession_3269048889845270929",
                "timestamp": 1545894520220,
                "type": "googLibjingleSession",
                "googInitiator": "false"
            },
            "bweforvideo": {
                "id": "bweforvideo",
                "timestamp": 1545894520220,
                "type": "VideoBwe",
                "googActualEncBitrate": "0",
                "googAvailableSendBandwidth": "300000",
                "googRetransmitBitrate": "0",
                "googAvailableReceiveBandwidth": "0",
                "googTargetEncBitrate": "0",
                "googBucketDelay": "0",
                "googTransmitBitrate": "0"
            },
            "googTrack_2cb93cd9-bd07-4d7e-b9ef-6cd98938e946": {
                "id": "googTrack_2cb93cd9-bd07-4d7e-b9ef-6cd98938e946",
                "timestamp": 1545894520220,
                "type": "googTrack",
                "googTrackId": "2cb93cd9-bd07-4d7e-b9ef-6cd98938e946"
            },
            "googCertificate_13:F0:37:B2:E9:FC:13:E4:99:E6:04:64:37:C6:6E:EE:35:ED:68:13:06:9C:C5:E8:B7:86:EF:D4:69:50:14:52": {
                "id": "googCertificate_13:F0:37:B2:E9:FC:13:E4:99:E6:04:64:37:C6:6E:EE:35:ED:68:13:06:9C:C5:E8:B7:86:EF:D4:69:50:14:52",
                "timestamp": 1545894520220,
                "type": "googCertificate",
                "googFingerprint": "13:F0:37:B2:E9:FC:13:E4:99:E6:04:64:37:C6:6E:EE:35:ED:68:13:06:9C:C5:E8:B7:86:EF:D4:69:50:14:52",
                "googFingerprintAlgorithm": "sha-256",
                "googDerBase64": "MIIBFjCBvaADAgECAgkAyfEQ48EoLfwwCgYIKoZIzj0EAwIwETEPMA0GA1UEAwwGV2ViUlRDMB4XDTE4MTIyNjA3MDgzOFoXDTE5MDEyNjA3MDgzOFowETEPMA0GA1UEAwwGV2ViUlRDMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh9uwkVl5SsfnXizk+g+ckdxFMEDdAZYv7wL7LJAgmw3BVoiIb0zKt0GI/6z3ziXC0we5ciASn9RfgHpfu5mA8TAKBggqhkjOPQQDAgNIADBFAiAfouU7BmpVbvSlAZev3ijR5yaI4BaF8yRVGt2IHIXTjgIhAPrEyzUjePEO9zd72EvCB1MhbbMS4u7r3CAdyBfgD+iJ"
            },
            "Channel-video-1": {
                "id": "Channel-video-1",
                "timestamp": 1545894520220,
                "type": "googComponent",
                "googComponent": "1",
                "remoteCertificateId": "googCertificate_81:6A:97:86:BB:67:DB:52:D1:19:B0:77:DF:59:82:F5:0C:BE:34:3C:E1:71:30:DD:4C:AD:7E:77:DA:2B:31:20",
                "selectedCandidatePairId": "Conn-video-1-0",
                "dtlsCipher": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                "localCertificateId": "googCertificate_13:F0:37:B2:E9:FC:13:E4:99:E6:04:64:37:C6:6E:EE:35:ED:68:13:06:9C:C5:E8:B7:86:EF:D4:69:50:14:52",
                "srtpCipher": "AES_CM_128_HMAC_SHA1_80"
            },
            "ssrc_1735385234_recv": {
                "id": "ssrc_1735385234_recv",
                "timestamp": 1545894520220,
                "type": "ssrc",
                "googContentType": "realtime",
                "googCaptureStartNtpTimeMs": "0",
                "googTargetDelayMs": "25",
                "packetsLost": "0",
                "googDecodeMs": "1",
                "googFrameHeightReceived": "480",
                "googFrameRateOutput": "20",
                "packetsReceived": "265",
                "ssrc": "1735385234",
                "googRenderDelayMs": "10",
                "googMaxDecodeMs": "2",
                "googTrackId": "2cb93cd9-bd07-4d7e-b9ef-6cd98938e946",
                "googFrameWidthReceived": "640",
                "codecImplementationName": "libvpx",
                "transportId": "Channel-video-1",
                "mediaType": "video",
                "googTimingFrameInfo": "388080465,-12,-12,-7,-6,-1,-12,-12,584006209,584006210,584006231,584006232,584006242,0,1",
                "googInterframeDelayMax": "65",
                "googCodecName": "VP8",
                "googFrameRateReceived": "20",
                "qpSum": "660",
                "framesDecoded": "34",
                "googNacksSent": "0",
                "googFirsSent": "0",
                "bytesReceived": "288615",
                "googCurrentDelayMs": "25",
                "googMinPlayoutDelayMs": "0",
                "googFrameRateDecoded": "20",
                "googJitterBufferMs": "13",
                "googPlisSent": "0"
            },
            "googCertificate_81:6A:97:86:BB:67:DB:52:D1:19:B0:77:DF:59:82:F5:0C:BE:34:3C:E1:71:30:DD:4C:AD:7E:77:DA:2B:31:20": {
                "id": "googCertificate_81:6A:97:86:BB:67:DB:52:D1:19:B0:77:DF:59:82:F5:0C:BE:34:3C:E1:71:30:DD:4C:AD:7E:77:DA:2B:31:20",
                "timestamp": 1545894520220,
                "type": "googCertificate",
                "googFingerprint": "81:6A:97:86:BB:67:DB:52:D1:19:B0:77:DF:59:82:F5:0C:BE:34:3C:E1:71:30:DD:4C:AD:7E:77:DA:2B:31:20",
                "googFingerprintAlgorithm": "sha-256",
                "googDerBase64": "MIIBFTCBvaADAgECAgkAhjPFqKcVQhwwCgYIKoZIzj0EAwIwETEPMA0GA1UEAwwGV2ViUlRDMB4XDTE4MTIyNjA3MDgzOFoXDTE5MDEyNjA3MDgzOFowETEPMA0GA1UEAwwGV2ViUlRDMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEF7z2TEeenab1lJnn4MpqeZ9A5tm12e218xweqfrpNVu8yrRiEePtJOmqdZegtgVE+C9NYPON08al1Gcg885X8DAKBggqhkjOPQQDAgNHADBEAiBOwilPhAogX7bDwNpGhiK2r2bhqxK5+ROLGl4M3xnCxAIgPU4pCjvwjZTlTJmBvuMoEHsR8CQLPDsT3dUmuFY1QXg="
            },
            "Cand-o5fZZoHH": {
                "id": "Cand-o5fZZoHH",
                "timestamp": 1545894520220,
                "type": "localcandidate",
                "stunKeepaliveRequestsSent": "0",
                "portNumber": "54656",
                "networkType": "lan",
                "ipAddress": "192.168.42.1",
                "stunKeepaliveResponsesReceived": "0",
                "stunKeepaliveRttTotal": "0",
                "transport": "udp",
                "candidateType": "host",
                "stunKeepaliveRttSquaredTotal": "0",
                "priority": "2122260223"
            },
            "Cand-P5B4Qw+e": {
                "id": "Cand-P5B4Qw+e",
                "timestamp": 1545894520220,
                "type": "localcandidate",
                "stunKeepaliveRequestsSent": "0",
                "portNumber": "54657",
                "networkType": "lan",
                "ipAddress": "192.168.28.1",
                "stunKeepaliveResponsesReceived": "0",
                "stunKeepaliveRttTotal": "0",
                "transport": "udp",
                "candidateType": "host",
                "stunKeepaliveRttSquaredTotal": "0",
                "priority": "2122194687"
            },
            "Cand-La47CCLl": {
                "id": "Cand-La47CCLl",
                "timestamp": 1545894520220,
                "type": "localcandidate",
                "stunKeepaliveRequestsSent": "0",
                "portNumber": "54658",
                "networkType": "lan",
                "ipAddress": "169.254.241.195",
                "stunKeepaliveResponsesReceived": "0",
                "stunKeepaliveRttTotal": "0",
                "transport": "udp",
                "candidateType": "host",
                "stunKeepaliveRttSquaredTotal": "0",
                "priority": "2122129151"
            },
            "Cand-+EQaG0Dl": {
                "id": "Cand-+EQaG0Dl",
                "timestamp": 1545894520220,
                "type": "localcandidate",
                "stunKeepaliveRequestsSent": "0",
                "portNumber": "54659",
                "networkType": "lan",
                "ipAddress": "192.168.131.174",
                "stunKeepaliveResponsesReceived": "0",
                "stunKeepaliveRttTotal": "0",
                "transport": "udp",
                "candidateType": "host",
                "stunKeepaliveRttSquaredTotal": "0",
                "priority": "2122063615"
            },
            "Conn-video-1-0": {
                "id": "Conn-video-1-0",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "4",
                "requestsReceived": "4",
                "googRemoteCandidateType": "local",
                "googReadable": "true",
                "googLocalAddress": "192.168.42.1:54656",
                "consentRequestsSent": "1",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "true",
                "requestsSent": "4",
                "googRemoteAddress": "192.168.42.1:54650",
                "googRtt": "0",
                "googActiveConnection": "true",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "315674",
                "responsesReceived": "4",
                "remoteCandidateId": "Cand-st6r4HAZ",
                "localCandidateId": "Cand-o5fZZoHH",
                "bytesSent": "2299",
                "packetsSent": "37"
            },
            "Cand-st6r4HAZ": {
                "id": "Cand-st6r4HAZ",
                "timestamp": 1545894520220,
                "type": "remotecandidate",
                "portNumber": "54650",
                "ipAddress": "192.168.42.1",
                "transport": "udp",
                "candidateType": "host",
                "priority": "2122260223"
            },
            "Conn-video-1-1": {
                "id": "Conn-video-1-1",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "3",
                "requestsReceived": "3",
                "googRemoteCandidateType": "local",
                "googReadable": "true",
                "googLocalAddress": "192.168.28.1:54657",
                "consentRequestsSent": "1",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "true",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.28.1:54651",
                "googRtt": "0",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "3",
                "remoteCandidateId": "Cand-wUzbwAwd",
                "localCandidateId": "Cand-P5B4Qw+e",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Cand-wUzbwAwd": {
                "id": "Cand-wUzbwAwd",
                "timestamp": 1545894520220,
                "type": "remotecandidate",
                "portNumber": "54651",
                "ipAddress": "192.168.28.1",
                "transport": "udp",
                "candidateType": "host",
                "priority": "2122194687"
            },
            "Conn-video-1-2": {
                "id": "Conn-video-1-2",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "3",
                "requestsReceived": "3",
                "googRemoteCandidateType": "local",
                "googReadable": "true",
                "googLocalAddress": "169.254.241.195:54658",
                "consentRequestsSent": "1",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "true",
                "requestsSent": "3",
                "googRemoteAddress": "169.254.241.195:54652",
                "googRtt": "0",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "3",
                "remoteCandidateId": "Cand-rIhT8GlX",
                "localCandidateId": "Cand-La47CCLl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Cand-rIhT8GlX": {
                "id": "Cand-rIhT8GlX",
                "timestamp": 1545894520220,
                "type": "remotecandidate",
                "portNumber": "54652",
                "ipAddress": "169.254.241.195",
                "transport": "udp",
                "candidateType": "host",
                "priority": "2122129151"
            },
            "Conn-video-1-3": {
                "id": "Conn-video-1-3",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "3",
                "requestsReceived": "3",
                "googRemoteCandidateType": "local",
                "googReadable": "true",
                "googLocalAddress": "192.168.131.174:54659",
                "consentRequestsSent": "1",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "true",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.131.174:54653",
                "googRtt": "0",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "3",
                "remoteCandidateId": "Cand-FDH/fs0O",
                "localCandidateId": "Cand-+EQaG0Dl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Cand-FDH/fs0O": {
                "id": "Cand-FDH/fs0O",
                "timestamp": 1545894520220,
                "type": "remotecandidate",
                "portNumber": "54653",
                "ipAddress": "192.168.131.174",
                "transport": "udp",
                "candidateType": "host",
                "priority": "2122063615"
            },
            "Conn-video-1-4": {
                "id": "Conn-video-1-4",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.28.1:54657",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.42.1:54650",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-st6r4HAZ",
                "localCandidateId": "Cand-P5B4Qw+e",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-5": {
                "id": "Conn-video-1-5",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "169.254.241.195:54658",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.42.1:54650",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-st6r4HAZ",
                "localCandidateId": "Cand-La47CCLl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-6": {
                "id": "Conn-video-1-6",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "169.254.241.195:54658",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.28.1:54651",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-wUzbwAwd",
                "localCandidateId": "Cand-La47CCLl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-7": {
                "id": "Conn-video-1-7",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.131.174:54659",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.42.1:54650",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-st6r4HAZ",
                "localCandidateId": "Cand-+EQaG0Dl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-8": {
                "id": "Conn-video-1-8",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.131.174:54659",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "192.168.28.1:54651",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-wUzbwAwd",
                "localCandidateId": "Cand-+EQaG0Dl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-9": {
                "id": "Conn-video-1-9",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.131.174:54659",
                "consentRequestsSent": "3",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "3",
                "googRemoteAddress": "169.254.241.195:54652",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-rIhT8GlX",
                "localCandidateId": "Cand-+EQaG0Dl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-10": {
                "id": "Conn-video-1-10",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.42.1:54656",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "192.168.28.1:54651",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-wUzbwAwd",
                "localCandidateId": "Cand-o5fZZoHH",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-11": {
                "id": "Conn-video-1-11",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.42.1:54656",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "169.254.241.195:54652",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-rIhT8GlX",
                "localCandidateId": "Cand-o5fZZoHH",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-12": {
                "id": "Conn-video-1-12",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.28.1:54657",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "169.254.241.195:54652",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-rIhT8GlX",
                "localCandidateId": "Cand-P5B4Qw+e",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-13": {
                "id": "Conn-video-1-13",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.42.1:54656",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "192.168.131.174:54653",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-FDH/fs0O",
                "localCandidateId": "Cand-o5fZZoHH",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-14": {
                "id": "Conn-video-1-14",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "192.168.28.1:54657",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "192.168.131.174:54653",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-FDH/fs0O",
                "localCandidateId": "Cand-P5B4Qw+e",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "Conn-video-1-15": {
                "id": "Conn-video-1-15",
                "timestamp": 1545894520220,
                "type": "googCandidatePair",
                "responsesSent": "0",
                "requestsReceived": "0",
                "googRemoteCandidateType": "local",
                "googReadable": "false",
                "googLocalAddress": "169.254.241.195:54658",
                "consentRequestsSent": "0",
                "googTransportType": "udp",
                "googChannelId": "Channel-video-1",
                "googLocalCandidateType": "local",
                "googWritable": "false",
                "requestsSent": "0",
                "googRemoteAddress": "192.168.131.174:54653",
                "googRtt": "3000",
                "googActiveConnection": "false",
                "packetsDiscardedOnSend": "0",
                "bytesReceived": "0",
                "responsesReceived": "0",
                "remoteCandidateId": "Cand-FDH/fs0O",
                "localCandidateId": "Cand-La47CCLl",
                "bytesSent": "0",
                "packetsSent": "0"
            },
            "timestamp": "2018-12-27T07:08:40.223Z"
        },
        1545894520223
    ],
    [
        "getstats",
        "PC_0",
        {
            "bweforvideo": {
                "googActualEncBitrate": "1719256",
                "googBucketDelay": "5",
                "googTransmitBitrate": "1749984"
            },
            "ssrc_1735385234_send": {
                "googEncodeUsagePercent": "25",
                "googAvgEncodeMs": "12",
                "framesEncoded": "237",
                "qpSum": "2216",
                "packetsSent": "2273",
                "bytesSent": "2503571"
            },
            "Conn-video-1-0": {
                "bytesReceived": "11967",
                "bytesSent": "2531268",
                "packetsSent": "2329"
            },
            "Conn-video-1-1": {
                "googLocalAddress": "169.254.241.195:54652",
                "googRemoteAddress": "169.254.241.195:54658",
                "remoteCandidateId": "Cand-4e/wC+0T",
                "localCandidateId": "Cand-iikkQign"
            },
            "Conn-video-1-2": {
                "responsesSent": "5",
                "requestsReceived": "5",
                "googReadable": "false",
                "googLocalAddress": "192.168.28.1:54651",
                "requestsSent": "5",
                "googRemoteAddress": "192.168.28.1:54657",
                "responsesReceived": "5",
                "remoteCandidateId": "Cand-NfrgNdYS",
                "localCandidateId": "Cand-pLC0a9Yl"
            },
            "Conn-video-1-3": {
                "googLocalAddress": "192.168.131.174:54653",
                "googRemoteAddress": "192.168.131.174:54659",
                "remoteCandidateId": "Cand-4x4QQxpK",
                "localCandidateId": "Cand-NqKUoTz8"
            },
            "Conn-video-1-6": {
                "consentRequestsSent": "5",
                "requestsSent": "5"
            },
            "Conn-video-1-7": {
                "consentRequestsSent": "5",
                "requestsSent": "5"
            },
            "Conn-video-1-8": {
                "consentRequestsSent": "5",
                "requestsSent": "5"
            },
            "timestamp": "2018-12-27T07:08:50.343Z"
        },
        1545894530343
    ]
];